// Code generated by ent, DO NOT EDIT.

package subreply

const (
	// Label holds the string label denoting the subreply type in the database.
	Label = "subreply"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the subreply in the database.
	Table = "subreplies"
)

// Columns holds all SQL columns for subreply fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
