// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/Faroukhamadi/likude/ent/subreply"
)

// Subreply is the model entity for the Subreply schema.
type Subreply struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Subreply) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case subreply.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Subreply", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Subreply fields.
func (s *Subreply) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subreply.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Subreply.
// Note that you need to call Subreply.Unwrap() before calling this method if this Subreply
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Subreply) Update() *SubreplyUpdateOne {
	return (&SubreplyClient{config: s.config}).UpdateOne(s)
}

// Unwrap unwraps the Subreply entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Subreply) Unwrap() *Subreply {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Subreply is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Subreply) String() string {
	var builder strings.Builder
	builder.WriteString("Subreply(")
	builder.WriteString(fmt.Sprintf("id=%v", s.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Subreplies is a parsable slice of Subreply.
type Subreplies []*Subreply

func (s Subreplies) config(cfg config) {
	for _i := range s {
		s[_i].config = cfg
	}
}
