// Code generated by ent, DO NOT EDIT.

package topicrelated

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Faroukhamadi/likude/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// TopicID applies equality check predicate on the "topic_id" field. It's identical to TopicIDEQ.
func TopicID(v int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTopicID), v))
	})
}

// RelatedTopicID applies equality check predicate on the "related_topic_id" field. It's identical to RelatedTopicIDEQ.
func RelatedTopicID(v int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRelatedTopicID), v))
	})
}

// TopicIDEQ applies the EQ predicate on the "topic_id" field.
func TopicIDEQ(v int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTopicID), v))
	})
}

// TopicIDNEQ applies the NEQ predicate on the "topic_id" field.
func TopicIDNEQ(v int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTopicID), v))
	})
}

// TopicIDIn applies the In predicate on the "topic_id" field.
func TopicIDIn(vs ...int) predicate.TopicRelated {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TopicRelated(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTopicID), v...))
	})
}

// TopicIDNotIn applies the NotIn predicate on the "topic_id" field.
func TopicIDNotIn(vs ...int) predicate.TopicRelated {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TopicRelated(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTopicID), v...))
	})
}

// RelatedTopicIDEQ applies the EQ predicate on the "related_topic_id" field.
func RelatedTopicIDEQ(v int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRelatedTopicID), v))
	})
}

// RelatedTopicIDNEQ applies the NEQ predicate on the "related_topic_id" field.
func RelatedTopicIDNEQ(v int) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRelatedTopicID), v))
	})
}

// RelatedTopicIDIn applies the In predicate on the "related_topic_id" field.
func RelatedTopicIDIn(vs ...int) predicate.TopicRelated {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TopicRelated(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRelatedTopicID), v...))
	})
}

// RelatedTopicIDNotIn applies the NotIn predicate on the "related_topic_id" field.
func RelatedTopicIDNotIn(vs ...int) predicate.TopicRelated {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TopicRelated(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRelatedTopicID), v...))
	})
}

// HasTopic applies the HasEdge predicate on the "topic" edge.
func HasTopic() predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(TopicTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TopicTable, TopicColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTopicWith applies the HasEdge predicate on the "topic" edge with a given conditions (other predicates).
func HasTopicWith(preds ...predicate.Topic) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(TopicInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TopicTable, TopicColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRelatedTopic applies the HasEdge predicate on the "related_topic" edge.
func HasRelatedTopic() predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RelatedTopicTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RelatedTopicTable, RelatedTopicColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRelatedTopicWith applies the HasEdge predicate on the "related_topic" edge with a given conditions (other predicates).
func HasRelatedTopicWith(preds ...predicate.Topic) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RelatedTopicInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RelatedTopicTable, RelatedTopicColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TopicRelated) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TopicRelated) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TopicRelated) predicate.TopicRelated {
	return predicate.TopicRelated(func(s *sql.Selector) {
		p(s.Not())
	})
}
