// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/Faroukhamadi/likude/ent/runtime.go

const (
	Version = "v0.10.2-0.20220712151345-6c8a1308ec2d"           // Version of ent codegen.
	Sum     = "h1:hTKIQC9HrDj9vi56+YTg4pdMy8t6R1d8re3qUm7+P7M=" // Sum of ent codegen.
)
